services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=
      - POSTGRES_CONTAINER=${POSTGRES_CONTAINER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - AI_SERVER_URL=http://ai:8000
      - SERVICE_AUTH_SECRET=${SERVICE_AUTH_SECRET}
    depends_on:
      - postgres
      - ai
  ai:
    build:
      context: ./ai-server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - SERVICE_AUTH_SECRET=${SERVICE_AUTH_SECRET}

  postgres:
    image: 'postgres:16'
    container_name: ${POSTGRES_CONTAINER}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data